# The recommended basic settings for GNN
out_dir: results
dataset:
  format: PyG
  name: GLAMMDataset
  task: graph
  task_type: regression
  transductive: false
  transform: none
  split_mode: custom
  encoder: false
  edge_dim: 5
train:
  batch_size: 32
  eval_period: 20
  ckpt_period: 100
model:
  type: gnn
  loss_fun: mse
  edge_decoding: dot
  graph_pooling: add
gnn:
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 256
  layer_type: nnconv
  stage_type: stack
  batchnorm: true
  act: prelu
  dropout: 0.0
  agg: add
  normalize_adj: false
optim:
  optimizer: adam
  base_lr: 0.001
  max_epoch: 5
